### ISSUE TITLE
Support data64 images

### ISSUE THREAD

**Issue by positlabs** [tumblr/tumblr.js#47]
The `requireOptions` for photo `postCreation` doesn't account for the `data64` option. Passing the image as `data64` produces this error.

```
Error: Missing one of: data,source
    at requireValidation (/Volumes/space/workspace/otherside-me_aura/aura-server/node_modules/tumblr.js/lib/tumblr.js:231:13)
    at Object.photo (/Volumes/space/workspace/otherside-me_aura/aura-server/node_modules/tumblr.js/lib/tumblr.js:31:7)
    at /Volumes/space/workspace/otherside-me_aura/aura-server/routes/tumblr.js:70:9
    at Layer.handle [as handle_request] (/Volumes/space/workspace/otherside-me_aura/aura-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/Volumes/space/workspace/otherside-me_aura/aura-server/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Volumes/space/workspace/otherside-me_aura/aura-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Volumes/space/workspace/otherside-me_aura/aura-server/node_modules/express/lib/router/layer.js:95:5)
    at /Volumes/space/workspace/otherside-me_aura/aura-server/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Volumes/space/workspace/otherside-me_aura/aura-server/node_modules/express/lib/router/index.js:330:12)
    at next (/Volumes/space/workspace/otherside-me_aura/aura-server/node_modules/express/lib/router/index.js:271:10)
```

[Adding base64 here](https://github.com/tumblr/tumblr.js/blob/master/lib/tumblr.js#L116) doesn't fix it, either.

`[Error: API error: 400 Bad Request]`

Here is my code. Using a `source` url posts the photo with no issues.

```
client.photo(req.body.blogname, {
		data64: req.body.image,
		// source: 'https://img.buzzfeed.com/buzzfeed-static/static/2014-04/enhanced/webdr03/4/16/enhanced-26552-1396642701-1.jpg?no-auto'
	}, function(){});
```

**Comment by oliver-j** [comment]
I have the same issue :(

**Comment by kmck** [comment]
`data64` should work in post creation now!

**Comment by positlabs** [comment]
Thanks @kmck! I will test eventually...
